### ISSUE TITLE
deploying from travis fails

### ISSUE THREAD

**Issue by igalic** [maestrodev/puppet-blacksmith#23]
in most of @puppet-community we use blacksmith to manage our releases.
however, right now, we cannot automate the deployment, because blacksmith fails when running from travis, always with the same issue. Here's a [failure](https://travis-ci.org/puppet-community/puppet-archive/jobs/93192396) from [puppet-archive](https://github.com/puppet-community/puppet-archive)

```
Deploying application
Uploading to Puppet Forge puppet/archive

travis_fold:end:dpl.3
No stash found.
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/puppet-blacksmith-3.3.1/lib/puppet_blacksmith/forge.rb:62:in `rescue in push!': Error uploading /home/travis/build/puppet-community/puppet-archive/pkg/puppet-archive-0.4.0.tar.gz to the forge https://forgeapi.puppetlabs.com [413 Request Entity Too Large]: { (Blacksmith::Error)
    "errors": ["413 Request Entity Too Large"]
}
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/puppet-blacksmith-3.3.1/lib/puppet_blacksmith/forge.rb:57:in `push!'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.10/lib/dpl/provider/puppet_forge.rb:38:in `push_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.10/lib/dpl/provider.rb:145:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.10/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.10/lib/dpl/provider.rb:145:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.10/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.10/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.10/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by igalic** [comment]
~side~ note: on travis we use ruby 1.9.3, on my system i use 2.1.6

**Comment by igalic** [comment]
interestingly, we're getting the exact same report when [pushing off of 2.1.6](https://travis-ci.org/puppet-community/puppet-archive/jobs/93197217)

n.b.: I really don't know how to just restrict it to one target… otherwise we'll get deployment failures on a travis build that runs later with the same version of ruby, but a different puppet version… and hence a failed build again.

**Comment by igalic** [comment]
this has been fixed by extending our .pmtignore to include .bundle
